### ISSUE TITLE
[code] Explore Normal Reconstruction using Moving Least Squares (MLS) with supplementary code using PCL 

### ISSUE THREAD

**Issue by sarrah-basta** [Shazam213/Drone-3d-topography#4]

**Comment by sarrah-basta** [comment]
Close the issue only after referencing the relevant commit id in the comments. The code should be committed on the main branch.

**Comment by unmani-shinde** [comment]
Commit ID: 8357d3025b2816f2441e95cbece6e8bc4fee5152
